# Generated by Django 3.1.1 on 2020-09-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200913_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
