# Generated by Django 3.1.1 on 2020-09-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200916_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='rating',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
